<a href="https://colab.research.google.com/github/KIISIISHERE/Operations-using-Numpy/blob/main/Operations_Using_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1. Create an array consisting of linearly spaced elements between 0 to 9
original_array = np.linspace(0, 9, 10, dtype=int)
print("Original Array:\n", original_array)

# 2. Replace all odd numbers in this array with -1 without modifying the original array
modified_array = np.where(original_array % 2 != 0, -1, original_array)
print("\nModified Array (odd numbers replaced with -1):\n", modified_array)

# 3. Create a new array that contains the original 1D array converted into a 2D array with two rows
two_dim_array = np.reshape(original_array, (2, 5))
print("\n2D Array with two rows:\n", two_dim_array)

# 4. Iterate through the original array and find the sum of all elements
total_sum = np.sum(original_array)
print("\nSum of all elements in the original array:", total_sum)


Original Array:
 [0 1 2 3 4 5 6 7 8 9]

Modified Array (odd numbers replaced with -1):
 [ 0 -1  2 -1  4 -1  6 -1  8 -1]

2D Array with two rows:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Sum of all elements in the original array: 45


✅ Quick Notes:
np.linspace(0, 9, 10, dtype=int) creates 10 evenly spaced integers from 0 to 9.

np.where() is used to replace odd numbers with -1 while keeping the original array unchanged.

np.reshape() is used to convert the 1D array into a 2D array with 2 rows and 5 columns.

np.sum() adds up all elements of the array.